name: sleep_well
description: A privacy-first sleep app for better bedtime routines
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  
  # Audio
  just_audio: ^0.9.40
  
  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  
  # Data Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Haptics (built into Flutter SDK)

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Testing
  mockito: ^5.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#0E1116"
    theme_color: "#5ED0B5"

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
